name: saatchi
favicon: null
layout_spectrum: 0.8056071544997394
typography_spectrum: 0.8943066890351474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8117944442201406
  lightness: 0.9571280723903328
  saturation: 0.7313194822054356
  rhythmicContrast: 0.4576493655331433
purpose: []
